-- ==============================================================================
-- AWS Student Builder Group — Classroom Resume Architecture (Supabase / Postgres)
-- Run this in your Supabase SQL Editor: https://supabase.com/dashboard/project/_/sql
-- ==============================================================================

-- 1. Create Candidates Table (Tracks identity, session, server start_time, set, and proctoring)
CREATE TABLE IF NOT EXISTS candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    usn TEXT,
    branch_sem TEXT,
    session_id TEXT UNIQUE NOT NULL,
    start_time TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    duration_seconds INTEGER DEFAULT 1500 NOT NULL, -- 25 minutes default
    challenge_id TEXT DEFAULT 'set_a' NOT NULL,
    set_name TEXT DEFAULT 'SET A' NOT NULL,
    status TEXT DEFAULT 'in_progress' NOT NULL, -- 'in_progress', 'submitted', 'time_expired'
    score INTEGER DEFAULT 0,
    total_possible INTEGER DEFAULT 15,
    integrity_risk TEXT DEFAULT 'LOW / CLEAN',
    time_taken_sec INTEGER DEFAULT 0,
    device TEXT,
    fullscreen_exits INTEGER DEFAULT 0,
    tab_switches INTEGER DEFAULT 0,
    copy_attempts INTEGER DEFAULT 0,
    paste_attempts INTEGER DEFAULT 0,
    ctrl_cmd_attempts INTEGER DEFAULT 0,
    text_selection_attempts INTEGER DEFAULT 0,
    question_timings JSONB DEFAULT '{}'::jsonb,
    question_violations JSONB DEFAULT '{}'::jsonb,
    events JSONB DEFAULT '[]'::jsonb,
    submitted_at TIMESTAMPTZ
);

-- 2. Create Answers Table (Linked to candidate by email, supports atomic upserts)
CREATE TABLE IF NOT EXISTS answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_email TEXT NOT NULL REFERENCES candidates(email) ON DELETE CASCADE,
    question_id TEXT NOT NULL,
    selected_option TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_candidate_question UNIQUE (candidate_email, question_id)
);

-- 3. Performance & Fast-Lookup Indexes
CREATE INDEX IF NOT EXISTS idx_candidates_email ON candidates(email);
CREATE INDEX IF NOT EXISTS idx_candidates_session_id ON candidates(session_id);
CREATE INDEX IF NOT EXISTS idx_candidates_status ON candidates(status);
CREATE INDEX IF NOT EXISTS idx_candidates_score ON candidates(score DESC);
CREATE INDEX IF NOT EXISTS idx_answers_candidate_email ON answers(candidate_email);
CREATE INDEX IF NOT EXISTS idx_answers_question_id ON answers(question_id);

-- 4. Row Level Security (RLS) Configuration
ALTER TABLE candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE answers ENABLE ROW LEVEL SECURITY;

-- Allow insert/update/select for public/backend API
DROP POLICY IF EXISTS "Allow all for candidates" ON candidates;
CREATE POLICY "Allow all for candidates" ON candidates 
    FOR ALL TO public USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for answers" ON answers;
CREATE POLICY "Allow all for answers" ON answers 
    FOR ALL TO public USING (true) WITH CHECK (true);

-- 5. Real-Time Classroom Proctoring & Evaluation View
CREATE OR REPLACE VIEW classroom_proctoring_dashboard AS
SELECT 
    c.id,
    c.email,
    c.name,
    c.usn,
    c.set_name,
    c.status,
    c.score || '/' || c.total_possible AS score,
    GREATEST(0, c.duration_seconds - EXTRACT(EPOCH FROM (NOW() - c.start_time))::INTEGER) AS seconds_remaining,
    c.integrity_risk,
    c.fullscreen_exits,
    c.tab_switches,
    c.copy_attempts,
    c.start_time,
    c.submitted_at,
    COUNT(a.id) AS answered_count
FROM candidates c
LEFT JOIN answers a ON c.email = a.candidate_email
GROUP BY c.id, c.email, c.name, c.usn, c.set_name, c.status, c.score, c.total_possible, c.duration_seconds, c.start_time, c.integrity_risk, c.fullscreen_exits, c.tab_switches, c.copy_attempts, c.submitted_at
ORDER BY c.score DESC, c.start_time ASC;
